### ISSUE TITLE
Support streaming with NO_COMPRESSION_64 and NO_COMPRESSION_32

### ISSUE THREAD

**Issue by ikreymer** [uktrade/stream-zip#58] opened 2023-07-12 13:16 UTC
Great library and easy to use API. However, I was a bit disappointed to discover that NO_COMPRESSION_64 and NO_COMPRESSION_32 options don't produce a streaming zip. For a library called `stream-zip`, having an option that, in fact, does not really produce a streaming zip seems a bit unexpected ;) (I must admit I should have read the documentation more clearly, but this is still very surprising, given the purpose of this library)

I am looking for a library to produce large streaming zip which packages other files with STORE instead of DEFLATE, and assumed the NO_COMPRESSION_* options would do so.

It's a bit of an usual chance, as uncompressed streaming seems easier than compressed streaming.

Would you be willing to add support for uncompressed STORE-mode streaming?

I assume it's not supported because the crc32 and size are stored in the local header before the data.. (edit: I see the data descriptor option is used for compressed data)

The way other tools handle this, for example `client-zip`, is to simply store 0 for the size and crc32 in the local record: https://github.com/Touffy/client-zip/blob/master/src/zip.ts#L124
and store the real values in central directory record which is computed after the stream is read.

I think this seems to work fine most tools, since the central directory is the main data used, and I think would be preferable to buffering the entire file - especially for zip64 since the use most likely is dealing with a very large file if requesting zip64 format.

Thanks again and happy to help test this!

**Comment by ikreymer** [comment] 2023-07-12 16:39
Create a quick patch that does uncompressed streaming, this works well for our case:
https://github.com/uktrade/stream-zip/compare/main...ikreymer:stream-zip:stream-uncompress?expand=1
happy to also do same for zip32 and open a PR if you'd like!

The resulting zip is readable and considered valid by `unzip -t`

**Comment by michalc** [comment] 2023-07-12 18:21
> Would you be willing to add support for uncompressed STORE-mode streaming?

Maybe... but...

> store 0 for the size and crc32 in the local record:

The main problem is that I think I think it makes the ZIP not stream unzip-able, which is a bit of a shame. Streaming unzippers I think need some way of knowing when they get to the end of the data. Without the size in local header, they can't know this for sure(?)

(Compressed data with DEFLATE doesn't need this since it indicates within the data stream when it reaches the end)

But... there might be a way of doing this. As of quite recently, there is the concept of "dynamic" modes, and specifically ZIP_AUTO. It accepts parameters. We could have something similar for NO_COMPRESSION_* that accepts the size and crc32? It might be a bit of a faff in situations to find these ahead of time, especially the crc32, but at least it makes it possible.

**Comment by ikreymer** [comment] 2023-07-12 18:41
> The main problem is that I think I think it makes the ZIP not stream unzip-able, which is a bit of a shame. Streaming unzippers I think need some way of knowing when they get to the end of the data. Without the size in local header, they can't know this for sure(?)

That's a fair point, if the goal is to be able to always stream unzip with `stream-unzip`. In general, I think ZIP files can be stream zipped and random-access unzipped (this is all our use case), but stream unzipping is more problematic (eg: https://github.com/thejoshwolfe/yauzl#no-streaming-unzip-api)

> (Compressed data with DEFLATE doesn't need this since it indicates within the data stream when it reaches the end)
> 
> But... there might be a way of doing this. As of quite recently, there is the concept of "dynamic" modes, and specifically ZIP_AUTO. It accepts parameters. We could have something similar for NO_COMPRESSION_* that accepts the size and crc32? It might be a bit of a faff in situations to find these ahead of time, especially the crc32, but at least it makes it possible.

What about adding a NO_COMPRESSION_STREAM_64 and NO_COMPRESSION_STREAM_32 that would stream zip but not be stream unzippable? That way, wouldn't break backwards compatibility.
Another option is to add 2 optional properties, so could include size and crc32 in addition to the 5 require properties? If at least the size is provided, then could still do the stream unzipping (though, I guess that wouldn't be spec conformant still..). Perhaps ZIP_AUTO could then choose NO_COMPRESSION_STREAM_* or NO_COMPRESSION_* based on whether the 6th size property is provided..

**Comment by michalc** [comment] 2023-07-12 20:03
> That's a fair point, if the goal is to be able to always stream unzip with stream-unzip.

Yes, but there are other stream unzippers as well. e.g. https://github.com/madler/sunzip and libarchive that you can call from Python using, for example, ctypes as in https://stackoverflow.com/a/74986842/1319998

> Another option is to add 2 optional properties, so could include size and crc32 in addition to the 5 require properties?

I think fairly not keen on this approach - currently the 5 properties are always required and used, so it feels odd a bit. More pro something mode-based if anything.

> What about adding a NO_COMPRESSION_STREAM_64 and NO_COMPRESSION_STREAM_32 that would stream zip but not be stream unzippable?

I'm torn... it adds another layer to the whole "what zip clients can open the zip" thing. The zip32/zip64 situation is complex enough...

Just to check though, are you especially not pro using ZIP_AUTO with level=0? That's very close to stored, but yes, a bit of overhead. And is it definitely not possible for you to determine size and crc32 ahead of time?

-----

Also on:

>  but stream unzipping is more problematic (eg: https://github.com/thejoshwolfe/yauzl#no-streaming-unzip-api)

From the link I see this:

> However, the Local File Headers are explicitly denounced in the spec as being unreliable copies of the Central Directory

I didn't realise this, although quickly looking through https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT now, it doesn't seem to really denounce it from what I can tell. And the ISO version https://nfoworks.org/notes/2013/04/n130401-13R5EoW9HY4ZvQH/n130401c11-ISO_IEC_21320-1_2015.pdf doesn't really seem to do that either from what I can tell.

**Comment by michalc** [comment] 2023-07-12 20:16
> Just to check though, are you especially not pro using ZIP_AUTO with level=0? 

Or... one of the other ZIP_ modes passing in a custom zlib object with level=0

**Comment by michalc** [comment] 2023-07-16 06:55
> What about adding a NO_COMPRESSION_STREAM_64 and NO_COMPRESSION_STREAM_32 that would stream zip but not be stream unzippable?

Just to communicate, I am more and more leaning to _not_ having a method where the resulting zip cannot be stream unzipped. The downsides of adding such a method I think are:

- I fear it's too much of a gotcha. Just like in this issue actually, I fear people not reading the docs, and getting bitten by it after ZIP files are generated, which is a bit late.
- It then adds to the list of trade offs you have to make when using the library if you do read the docs.
- And it's not one of those things where you can tell the client "oh just upgrade to a more recent version" - using a stream unzipper is a sort of core architectural choice.

While there are alternatives that I think avoid these:

- Passing "level=0" is an option right now which will disable compression in a stream unzip friendly way, at the cost of a few extra bytes (I think something like 1 extra bytes every 10k? It's quite low...). So I think a reasonable work around exists now for most cases. If there was some client that didn't support DEFLATE, or if the overhead was bigger, I might have a different opinion, but I think it's a very small overhead and I know of no such client.
- Adding a dynamic method of: `NO_COMPRESSION_32(uncompressed_size, crc_32)` say would cover a few more cases. Although I suspect crc_32 might be a bit annoying to calculate sometimes. But if files are stored on S3 say, then it looks like CRC32 can be added as a trailer https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html#API_PutObject_RequestSyntax on upload to S3, and so still calculated on the fly. I don't think I've seen an HTTP trailer used in the wild though...so don't know if there are some issues here. And of course, not everyone uses S3!

But yes... the case of wanting to stream write a zip file with STORED members without knowing both the uncompressed size and crc32 ahead of time, that would be left essentially as a wontfix. But: am curious as to what the specifics of the consequences of this would be though - what pain does it cause, what does it make difficult or impossible etc.

**Comment by ikreymer** [comment] 2023-07-16 09:30
> But yes... the case of wanting to stream write a zip file with STORED members without knowing both the uncompressed size and crc32 ahead of time, that would be left essentially as a wontfix. But: am curious as to what the specifics of the consequences of this would be though - what pain does it cause, what does it make difficult or impossible etc.

We have a packaging format that uses ZIP to package smaller files into a [distributable package](https://specs.webrecorder.net/wacz/1.1.1/#zip-compression). The format is accessed via random access: seek to read the central directory, then get file offsets in the zip, then offsets into each file from the beginning. Using STORE, we can seek from beginning of the file offset to get the data. Using DEFLATE with compression 0 could in theory work, but would have to change the format to also support this, and readers of the format would need to support both STORE and DEFLATE level 0, which just complicates the format spec and provides no benefit since the data must be uncompressed for it to work at all. I don't think its an option to use DEFLATE level 0 for this reason.

> I fear it's too much of a gotcha. Just like in this issue actually, I fear people not reading the docs, and getting bitten by it after ZIP files are generated, which is a bit late.

I very much disagree, as I was bitten by the current behavior! The library says 'Python function to construct a ZIP archive on the fly - without having to store the entire ZIP in memory or disk.' and it has an option called NO_COMPRESSION_64, so I thought it would do exactly as advertised. On the contrary, the library does the exact opposite -- it in fact stores the entire file in memory. Worse, if you're asking for zip64, chances are, you know you're like dealing with very large files (in our case, likely tens or hundreds of GB), which the library is more than happy to buffer entirely into memory!

Not everyone who finds this library needs streaming *unzip*, but probably they are looking for *streaming zip* functionality w/o unbounded buffering of large files.

I think having options to do both would perhaps most helpful for different use cases.

**Comment by michalc** [comment] 2023-07-16 09:49
> The format is accessed via random access: seek to read the central directory, then get file offsets in the zip, then offsets into each file from the beginning. Using STORE, we can seek from beginning of the file offset to get the data.

Oooh... I have to admit, I never considered random access within a member file. Tricky to do this with DEFLATE.

> I very much disagree, as I was bitten by the current behavior! 

Ah I more mean bitten by making ZIPs that can't be stream unzipped. It sounds like this isn't important for you, but I don't want to go and introduce gotchas for others.

Will continue to ponder...

**Comment by michalc** [comment] 2023-07-16 09:58
> Adding a dynamic method of: NO_COMPRESSION_32(uncompressed_size, crc_32)

Would you be able to use such a dynamic method so we can have our cake and eat it too? It would mean the file can be both stream written and stream read...

**Comment by michalc** [comment] 2023-07-16 12:07
One thing I'm curious about... On the wacz format, it looks like from https://specs.webrecorder.net/wacz/1.1.1/#zip-compression

> All archive/ files should be stored in ZIP with 'STORE' mode.

But from https://specs.webrecorder.net/wacz/1.1.1/#archive

> The archive directory MUST contain one or more files in the [[WARC](https://specs.webrecorder.net/wacz/1.1.1/#bib-warc)] format. The files SHOULD use the .warc file extension unless they are GZIP encoded in which case they MUST use the .warc.gz file extension.

So it looks like readers have to support not being able to seek into the STORED file anyway, since they have to support the STORED file being gz-encoded?

**Comment by michalc** [comment] 2023-07-16 12:11
Actually more curiosity - can the warc files inside the zip themselves made in a streaming way?

**Comment by michalc** [comment] 2023-07-16 13:17
> Adding a dynamic method of: NO_COMPRESSION_32(uncompressed_size, crc_32)

Have done this in https://github.com/uktrade/stream-zip/pull/63

**Comment by michalc** [comment] 2023-07-16 18:48
I know I'm not waiting for your answers, but I've pondered a bit more now...

... And although I see that it is useful in some circumstances to make STORED members in a streaming way with no up-front knowledge of the size and CRC 32, I'm going to treat that as beyond the scope of this project, because doing so makes ZIP files that can't be stream unzipped. The scope has to be limited somewhere, and I think I'm pro the line being drawn at adding behaviour that makes the files generated not stream unzippable.

I understand that might not be great news for your use case, but I'm happy to advise on what there is in stream-unzip, how to find the size and/or CRC 32 say to use `NO_COMPRESSION_32(uncompressed_size, crc_32)` (which might be trivial, but you never know...), or to give some thoughts on some other workaround.

**Closed by michalc** 2023-07-16 18:48 UTC

**Comment by ikreymer** [comment] 2023-07-18 16:36
That is a bit disappointing, as we'll have to use a fork, which works of course or find a different library to do this...

I would then suggest removing 'NO_COMPRESSION_64' and only having 'NO_COMPRESSION_64_BUFFERED' and 'NO_COMPRESSION_64_STREAMING' (and probably same for 32) so user does get bitten by unexpected behavior. I can't imagine a situation where a user would want to buffer a 4GB+ file so that should definitely not be a default behavior for NO_COMPRESSION_64 imo.

The WARC files are themselves gzip compressed, but as far as ZIP is concerned, they're added as STORE, because they're just files packaged into the ZIP. We're combining two formats: WARC and ZIP to create a package (WACZ) that is designed to be random-access readable. WARCs themselves are not random-access readable but can streamed (they're just concatenated gzip members). The point of this format is to provide a random-access readable format using ZIPs + their contents. I see you have a sqlite-s3-query implementation - the idea is very similar, we only use HTTP range requests to read the data from a potentially very large zip! That's why the streaming trade-off that you've proposed doesn't really make sense for us - the data is *only* ever read via random access and *never* stream-unzipped.

**Comment by michalc** [comment] 2023-07-18 17:39
> we'll have to use a fork, which works of course or find a different library to do this...

Ah understood

> WARCs themselves are not random-access readable but can streamed (they're just concatenated gzip members). The point of this format is to provide a random-access readable format using ZIPs + their contents

I can't help but wonder now... since it seems that [WACZ allows other files in the ZIP as DEFLATE](https://specs.webrecorder.net/wacz/1.1.1/#zip-compression), then you need some sort of HTTP-range friendly ZIP reader that supports DEFLATE members. So it's not a meaningful simplification to forbid DEFLATE on the things that aren't random access readable anyway?

>  I can't imagine a situation where a user would want to buffer a 4GB+ file so that should definitely not be a default behavior for NO_COMPRESSION_64 imo.

Very true

**Comment by michalc** [comment] 2023-07-18 19:22
> I would then suggest removing 'NO_COMPRESSION_64' and only having 'NO_COMPRESSION_64_BUFFERED' and 'NO_COMPRESSION_64_STREAMING' (and probably same for 32) so user does get bitten by unexpected behavior. 

Actually I'm now wondering whether to completely remove NO_COMPRESSION_64 and NO_COMPRESSION_32

- Users can roll their own versions using NO_COMPRESSION_64(uncompressed_size, crc_32) and NO_COMPRESSION_32(uncompressed_size, crc_32) respectively
- They introduce gotchas
- It'll keep this library more minimal
- And specifically, all supplied modes would be streaming. Any non-streaming-behaviour in order to find the size or crc32 would be out of this library.

**Comment by michalc** [comment] 2023-07-19 05:09
Ah but if the user already has the binary contents in a single `bytes` instance, `contents` say, then much simpler:
```
chunks = (contents,)
uncompressed_size = len(contents)
crc_32 = zlib.crc32(contents)
```

**Comment by mdineen** [comment] 2024-01-12 19:42
The pain it causes: my users often download archives comprised of files > 50GB with a total size > 1TB. The zip file keeps them in a single file, organized by internal folders. 

We need to be able to handle files up to the limit of S3 keys and zip files up to their 5TB/ 16EB limits respectively, which requires that we buffer nothing more than is necessary on the server, and produce a valid archive. I don't require that it be stream-unzippable and I can't handle the overhead that making it so would require. I need to stream in keys and stream out a zip file.

**Comment by michalc** [comment] 2024-01-12 20:57
@mdineen 

>  I need to stream in keys and stream out a zip file.

So you can do this right now with stream-zip:

1. With the ZIP_* methods. If you don't want to compress, you can still avoid it using https://stream-zip.docs.trade.gov.uk/advanced-usage/#custom-zlib-options. But yes: there is a small amount of overhead in the final output. I can't remember exactly, something like 3 bytes of overhead every 64k bytes, + 1 byte? Something like that...

2. With the NO_COMPRESSION_* methods that accept a length and CRC32. The length in your case you can get from S3... but yes, the CRC32 you would have to have pre-compute.

Are either of these feasible in your case?

**Comment by mdineen** [comment] 2024-01-12 22:19
1. I will try this
2. Not preferable to calculation on demand
  - we want to avoid unnecessary compute for files that won't be downloaded in a zip
  - io-bound CRC32 task process will delay archive availability until all checksums are available

**Comment by michalc** [comment] 2024-01-13 07:09
@mdineen 

> 2. Not preferable to calculation on demand

Yeah it's awkward...

> my users often download archives comprised of files > 50GB with a total size > 1TB
> [...] We need to be able to handle S3 keys and zip files up to their 5TB/ 16EB limits respectively

I am curious - are you able to share some details on your use case/situation?

**Comment by mdineen** [comment] 2024-01-13 14:48
We're serving the legal sector with a filesharing platform with no size limits. User A will upload thousands of files ranging from a few KB to 100s of GB in an app-defined folder structure. User B will then download the entire folder tree as a zip file. We use the zip format to maintain the folder structure and to allow user B to keep the entire archive as a single file.

A single matter could span years and still require that an uploaded folder tree be downloadable as an archive without having to compute checksums in advance. Using EC2 to pre-calculate a checksum on an S3 keys takes ~30s/GB. All that IO is unnecessary when the streaming code is already reading all the bytes and the CRC32 is stored after. My test archive is 250 GB with 5 files @ 50 GB each, so I need over 2 hours of precomputation time to cache the crc32s. That doesn't scale.

**Comment by michalc** [comment] 2024-01-13 15:21
Ah thanks for the details. All good to know.

So I would think the ZIP_64 or ZIP_AUTO methods should be able to handle those cases. Again just for curiosity/for the future really - are you deliberately wanting to avoid compressing the files in this case, or does it not matter?

>  zip files up to their 5TB/ 16EB limits respectively
>  User B will then download the entire folder tree as a zip file.

One thing I'm again curious about here: the users have  ~16EB of space locally to store a single file, and are able to use it? My world is... considerably smaller...

> so I need over 2 hours of precomputation time to cache the crc32s. That doesn't scale.

The one thing that crosses my mind here is the files must get to S3 somehow? Can the crc32s be computed on the way in? (With a one time job for anything that's already there). It's not obvious to me that this can't be done in a way that would be as scalable as getting the files into S3 in the first place.

> All that IO is unnecessary when the streaming code is already reading all the bytes and the CRC32 is stored after

Just for completeness really so everyone, including people looking at this later, are on the same page: the crc32 is stored after the data for the ZIP_* methods, but before the data for the NO_COMPRESSION_* methods.

**Comment by mdineen** [comment] 2024-01-13 15:51
We have avoided compression to ensure that there is no scalability limit based on CPU. Clients' disk space is at less of a premium than AWS EC2 time.

In practice the maximum archive size has been ~1TB. Mean size is closer to 180 GB. The solution we're looking for should ideally be scalable to the limit of the zip file specification. We're trying to replace nginx mod_zip, which scales up to these limits without appreciable memory or CPU overhead.

We've used cryptjs in our web app to capture the crc32 of the file at upload time, which could be an effective method going forward but makes legacy file sources and the decade of client data we have stored so far unusable.

Thanks for that clarification. Going to implement a test with ZIP_AUTO and post the comparison to my test with a node/express candidate written for this project as well.

**Comment by mdineen** [comment] 2024-01-13 20:32
As promised, here is my app.py for a uWSGI runtime:

```python
from datetime import datetime
from stream_zip import stream_zip, ZIP_64
import boto3
import zlib

def application(env, start_response):
    now = datetime.now()

    # AWS S3 Configuration
    s3_client = boto3.client('s3', aws_access_key_id=KEY_ID, aws_secret_access_key=SECRET_KEY)
    bucket_name = BUCKET

    # List of S3 keys to be zipped
    s3_keys = [ 
        'dd/c/ed3e6aed-e63e-438e-997e-503b599e0ddc',
        '61/5/59f9e614-d7dd-456a-adcf-48ed97ee2615',
        '71/9/b9fae65c-8a97-4841-8158-e10447f71719',
        'f4/a/bbf8a239-9102-4093-a3f6-7c1b110cdf4a',
        'ec/9/5f4d9b86-94f0-43fb-a8b7-4e21991daec9',
    ]   

    # Retrieve the streams from S3
    def member_files():
        for key in s3_keys:
            yield (key, now, 0o600, ZIP_64, s3_client.get_object(Bucket=bucket_name, Key=key)['Body'])

    # Set the headers
    headers = [('Content-Type', 'application/zip'),
               ('Content-Disposition', 'attachment; filename="large_file.zip"')]
    start_response('200 OK', headers)

    # Stream the zipped content
    get_compressobj = lambda: zlib.compressobj(level=0)
    return stream_zip(member_files(), get_compressobj=get_compressobj, chunk_size=512*1024*1024)
```

Using the 512MB buffer demonstrates tha this code is buffering the chunks, and the pattern of changes during the download says the same. The default chunk size of 64k is much too small for S3.

**Comment by michalc** [comment] 2024-01-13 20:49
> Am I missing anything?

The only thing that leaps out at me is this:

> The default chunk size of 64k is much too small for S3.

I'm surprised this affects it - I think I have fetched from S3 and zipped the results with the default chunk size fine. By my understanding, S3 shouldn't even be aware of it... at least directly.

Potentially it would be aware indirectly because it could affect performance of the Python code, so affects how fast it pulls bytes from the socket, which would then affect the speed that S3 sends its bytes/packets on a TCP level. (I have to admit I don't fully know what I'm talking about here...)

What happens when you leave it as the default?

**Comment by michalc** [comment] 2024-01-13 20:51
Ah one other thing... I have experienced some odd issues with ZIP_64 and Safari...

- Safari unzips ZIP files by default (which is annoying at the best of times...)
- But when the first file in a ZIP is ZIP_64, it seems to just unzip one file and that's it. The others are lost

Maybe I'm out of date admittedly

**Comment by mdineen** [comment] 2024-01-13 21:43
> What happens when you leave it as the default?

The download speed reduces to < 100 KB/s. It seems to make an API request for every chunk, each of which has headers and gets TLS'd and authenticated by S3. 250GB / 64KB = 4.2 M API calls. 

> Safari unzips ZIP files by default (which is annoying at the best of times...)

https://discussions.apple.com/thread/253077187?sortBy=best

> But when the first file in a ZIP is ZIP_64, it seems to just unzip one file and that's it. The others are lost

If you're certain those zips aren't corrupt, I recommend a different tool. The OS file browsers support ZIP, but in the size ranges we're creating they're flaky. We use 7-zip on Windows 11 to test the large zips, which is very effective.

The way this works with the 512 MB chunk size is quite choppy:

https://github.com/uktrade/stream-zip/assets/1494976/67212250-2e5f-409b-9728-d258f992bfa0

**Comment by michalc** [comment] 2024-01-13 21:56
> > What happens when you leave it as the default?

> It seems to make an API request for every chunk

Woah... nothing in my mental model suggest that this is possible. All stream-zip is doing it iterating over the iterable of `bytes` instances that are passed to it, which in this case is `s3_client.get_object(Bucket=bucket_name, Key=key)['Body']`. So a slightly more manual version of this:

```python
for chunk in s3_client.get_object(Bucket=bucket_name, Key=key)['Body']:
    # do stuff
```
And then `chunk_size` controls subsequent processing of each `chunk` - how they are split or aggregated. So for that processing to then result in a new HTTP request to S3... there would have to be something very magical going on.

> https://discussions.apple.com/thread/253077187?sortBy=best
> If you're certain those zips aren't corrupt, I recommend a different tool. The OS file browsers support ZIP, but in the size ranges we're creating they're flaky. We use 7-zip on Windows 11 to test the large zips, which is very effective.

Oh yeah - just wanted to warn in case your users used Safari to download the files you're making - I guess I think in a lot of cases telling users to change their browser settings is not a good option.

> The way this works with the 512 MB chunk size is quite choppy:

I would expect quite a lot of choppyness with such a chunk size because it would gather 512MB, output it to the user, and then only gather 512MB. There would be very little effective parallelism between getting stuff from S3, and sending it to the user as well because I think the various buffers involved would be way way smaller than 512MB

**Comment by michalc** [comment] 2024-01-13 21:59
> > What happens when you leave it as the default?

> The download speed reduces to < 100 KB/s

Interesting/surprising... I guess I would be curious as to what happens if you reduce it further, even to like 8k

**Comment by michalc** [comment] 2024-01-13 22:31
> The download speed reduces to < 100 KB/s

Or... what happens if you remove the web app part of it, and just run it from a Python script?

**Comment by mdineen** [comment] 2024-01-13 23:14
The issue appears to be with how boto fulfils stream requests. Rather than returning the streaming http response for the whole key, it create a request for each range (chunk) requested. 

Trying a somewhat different approach using boto to sign, and requests to download. It looks to provide the exact behaviour we want and makes only 1 API request per file.

```python
from datetime import datetime
from stream_zip import stream_zip, ZIP_64
import io
import boto3
import requests
import zlib

def application(env, start_response):
    now = datetime.now()

    # AWS S3 Configuration
    s3_client = boto3.client('s3', aws_access_key_id=KEY_ID, aws_secret_access_key=SECRET_KEY)
    bucket_name = BUCKET

    sign_url = lambda key: s3_client.generate_presigned_url('get_object', Params={'Bucket': bucket_name, 'Key': key}, ExpiresIn=6000)

    # List of S3 keys to be zipped
    s3_keys = [
        'dd/c/ed3e6aed-e63e-438e-997e-503b599e0ddc',
        '61/5/59f9e614-d7dd-456a-adcf-48ed97ee2615',
        '71/9/b9fae65c-8a97-4841-8158-e10447f71719',
        'f4/a/bbf8a239-9102-4093-a3f6-7c1b110cdf4a',
        'ec/9/5f4d9b86-94f0-43fb-a8b7-4e21991daec9',
    ]

    # Retrieve the streams from S3
    def member_files():
        for key in s3_keys:
            url = sign_url(key)
            yield (key, now, 0o600, ZIP_64, get_s3_stream(url))

    # Set the headers
    headers = [('Content-Type', 'application/zip'),
               ('Content-Disposition', 'attachment; filename="large_file.zip"')]
    start_response('200 OK', headers)

    # Stream the zipped content
    get_compressobj = lambda: zlib.compressobj(level=0)
    return stream_zip(member_files(), get_compressobj=get_compressobj)

def get_s3_stream(presigned_url):
    with requests.get(presigned_url, stream=True) as response:
        response.raise_for_status()
        for chunk in response.iter_content(chunk_size=8192):
            yield chunk
```

**Comment by michalc** [comment] 2024-01-13 23:24
> Please note I'm yielding 8k chunks here, and it's working very well so far.

Ah good!

> The issue appears to be with how boto fulfils stream requests. Rather than returning the streaming http response for the whole key, it create a request for each range (chunk) requested.

Can I ask how you determined this? Is this documented anywhere? I know S3 and boto supports range requests, but I thought you had to be explicit.

**Comment by mdineen** [comment] 2024-01-14 01:06
> Can I ask how you determined this? Is this documented anywhere? I know S3 and boto supports range requests, but I thought you had to be explicit.

If you turn on debug logging for boto you can see the requests in the logging. We first discovered this working with pypdf using automatic page detection, which reads the stream one byte at a time. Every read(1) to the body creates a few kb of api traffic.

```python
logging.basicConfig(level=logging.DEBUG)
boto3.set_stream_logger('boto3.resources', logging.DEBUG)
boto3.set_stream_logger('botocore', logging.DEBUG)

s3 = boto3.client('s3')
response = s3.get_object(...)
```

**Comment by mdineen** [comment] 2024-01-14 02:06
Initial tests look very good! Once the implementation is cleaned up I'll submit it for your examples if it would be helpful.

**Comment by michalc** [comment] 2024-01-14 05:48
> >Can I ask how you determined this? Is this documented anywhere? I know S3 and boto supports range requests, but I thought you had to be explicit.

> If you turn on debug logging for boto you can see the requests in the logging. 

So just done this...

```python
import logging
import boto3

logging.basicConfig(level=logging.DEBUG)
boto3.set_stream_logger('boto3.resources', logging.DEBUG)
boto3.set_stream_logger('botocore', logging.DEBUG)

s3 = boto3.client('s3')
response = s3.get_object(
    Bucket='...'
    Key='...'
)
for chunk in response['Body']:
    print(len(chunk))
```
and for good measure one with manual read calls
```python
import os
import logging
import boto3

logging.basicConfig(level=logging.DEBUG)
boto3.set_stream_logger('boto3.resources', logging.DEBUG)
boto3.set_stream_logger('botocore', logging.DEBUG)

s3 = boto3.client('s3')
response = s3.get_object(
    Bucket='...', 
    Key='...',
)
for chunk in iter(lambda: response['Body'].read(1024), b''):
    print(len(chunk))
```
and in both I see loads of initial botocore and urllib3 logs, showing intial HTTP requests. But then just a load of:
```
1024
```
until it ends. Which is what I expected really - the response of a single HTTP request is streamed out, and no evidence of a API request per chunk. Also did it with `read(1)` and that's similar - no API calls intermingled.

> Once the implementation is cleaned up I'll submit it for your examples if it would be helpful.

I think I would need to really understand why it's needed over just using boto3 more directly, e.g. see boto3 _not_ streaming out a request/response

**Comment by mdineen** [comment] 2024-01-14 20:17
> > What happens when you leave it as the default?

> The download speed reduces to < 100 KB/s

I can't reproduce this anymore. After removing the size arg the download is working smoothly and very fast. 

Sorry for misreporting this. While creating the test code I iterated on the member_files generator a few times and could have been closing the stream on completion. On the bright side, I have a great reference implementation that supports huge files, plus I can use S3 keys or http endpoints as file sources.

```diff
-     return stream_zip(member_files(), get_compressobj=get_compressobj, chunk_size=512*1024*1024)
+     return stream_zip(member_files(), get_compressobj=get_compressobj)
```

**Comment by michalc** [comment] 2024-01-14 22:06
> Sorry for misreporting this

All good! Please keep the reports coming

> On the bright side, I have a great reference implementation that supports huge files

It's good to know for me too - I know stream-zip works enough for our use cases/sizes, but it's hard to get an idea of what other people are using this for, what sort of sizes/constraints they're working with, that sort of thing.

**Comment by Wamy-Dev** [comment] 2024-01-24 02:26
> The issue appears to be with how boto fulfils stream requests. Rather than returning the streaming http response for the whole key, it create a request for each range (chunk) requested.
> 
> Trying a somewhat different approach using boto to sign, and requests to download. It looks to provide the exact behaviour we want and makes only 1 API request per file.
> 
> ```python
> from datetime import datetime
> from stream_zip import stream_zip, ZIP_64
> import io
> import boto3
> import requests
> import zlib
> 
> def application(env, start_response):
>     now = datetime.now()
> 
>     # AWS S3 Configuration
>     s3_client = boto3.client('s3', aws_access_key_id=KEY_ID, aws_secret_access_key=SECRET_KEY)
>     bucket_name = BUCKET
> 
>     sign_url = lambda key: s3_client.generate_presigned_url('get_object', Params={'Bucket': bucket_name, 'Key': key}, ExpiresIn=6000)
> 
>     # List of S3 keys to be zipped
>     s3_keys = [
>         'dd/c/ed3e6aed-e63e-438e-997e-503b599e0ddc',
>         '61/5/59f9e614-d7dd-456a-adcf-48ed97ee2615',
>         '71/9/b9fae65c-8a97-4841-8158-e10447f71719',
>         'f4/a/bbf8a239-9102-4093-a3f6-7c1b110cdf4a',
>         'ec/9/5f4d9b86-94f0-43fb-a8b7-4e21991daec9',
>     ]
> 
>     # Retrieve the streams from S3
>     def member_files():
>         for key in s3_keys:
>             url = sign_url(key)
>             yield (key, now, 0o600, ZIP_64, get_s3_stream(url))
> 
>     # Set the headers
>     headers = [('Content-Type', 'application/zip'),
>                ('Content-Disposition', 'attachment; filename="large_file.zip"')]
>     start_response('200 OK', headers)
> 
>     # Stream the zipped content
>     get_compressobj = lambda: zlib.compressobj(level=0)
>     return stream_zip(member_files(), get_compressobj=get_compressobj)
> 
> def get_s3_stream(presigned_url):
>     with requests.get(presigned_url, stream=True) as response:
>         response.raise_for_status()
>         for chunk in response.iter_content(chunk_size=8192):
>             yield chunk
> ```
> 
> Please note I'm yielding 8k chunks here, and it's working very well so far.

Is there a way to get total size so users can now how long until the download is complete?

**Comment by michalc** [comment] 2024-01-24 20:15
@Wamy-Dev 

> Is there a way to get total size so users can now how long until the download is complete?

If you're compressing the files, no, because the total size cannot in general be known until (just before) the very end of the generation of the zip file

If you're not compressing, then probably yes... Does https://github.com/uktrade/stream-zip/issues/21 have anything that helps?
